export const metadata = [
  { path: "game/1v1-lol", title: "1v1.LOL | nate-games" },
  { path: "game/justfall-lol", title: "JustFall.LOL | nate-games" },
  { path: "game/cluster-rush", title: "Cluster Rush | nate-games" },
  { path: "game/flash-sonic", title: "Flash Sonic | nate-games" },
  { path: "game/subway-surfers", title: "Subway Surfers | nate-games" },
  { path: "game/bottle-flip-3d", title: "Bottle Flip 3D | nate-games" },
  { path: "game/tiny-fishing", title: "Tiny Fishing | nate-games" },
  {
    path: "game/worlds-hardest-game",
    title: "Worlds Hardest Game | nate-games",
  },
  {
    path: "game/worlds-hardest-game-3",
    title: "Worlds Hardest Game 3 | nate-games",
  },
  { path: "game/slope", title: "Slope | nate-games" },
  { path: "game/slope-3", title: "Slope 3 | nate-games" },
  { path: "game/tunnel-rush", title: "Tunnel Rush | nate-games" },
  { path: "game/tunnel-rush-2", title: "Tunnel Rush 2 | nate-games" },
  { path: "game/tetris", title: "Tetris | nate-games" },
  { path: "game/paper-io-2", title: "Paper.io 2 | nate-games" },
  { path: "game/funny-shooter-2", title: "Funny Shooter 2 | nate-games" },
  { path: "game/crossy-road", title: "Crossy Road | nate-games" },
  { path: "game/moto-x3m", title: "Moto X3M | nate-games" },
  { path: "game/2048", title: "2048 | nate-games" },
  { path: "game/lazy-jump-3d", title: "Lazy Jump 3D | nate-games" },
  { path: "game/stack", title: "Stack | nate-games" },
  { path: "game/stickman-hook", title: "Stickman Hook | nate-games" },
  { path: "game/fruit-ninja", title: "Fruit Ninja | nate-games" },
  { path: "game/stair-race-3d", title: "Stair Race 3D | nate-games" },
  { path: "game/poor-eddie", title: "Poor Eddie | nate-games" },
  { path: "game/monkey-mart", title: "Monkey Mart | nate-games" },
  { path: "game/om-nom-run", title: "Om Nom Run | nate-games" },
  { path: "game/pac-man", title: "Pac-Man | nate-games" },
  { path: "game/ducklings-io", title: "Ducklings.io | nate-games" },
  {
    path: "/",
    title: "nate-games",
    description:
      "Your ultimate hub for unblocked games, and more! Immerse yourself in a world of gaming experiences - perfect for students & dedicated gamers!",
  },
  { path: "dev/adding-games", title: "Adding Games | nate-games" },
  { path: "dev/convert", title: "Image Converter | nate-games" },
  { path: "about", title: "About | nate-games" },
  { path: "games", title: "Games | nate-games" },
  { path: "*", title: "404" },
  {
    path: "/",
    title: "nate-games",
    description:
      "Your ultimate hub for unblocked games, and more! Immerse yourself in a world of gaming experiences - perfect for students & dedicated gamers!",
  },
  { path: "dev/adding-games", title: "Adding Games | nate-games" },
  { path: "dev/convert", title: "Image Converter | nate-games" },
  { path: "about", title: "About | nate-games" },
  { path: "games", title: "Games | nate-games" },
  { path: "*", title: "404" },
];
